name: Release Helm Charts

on:
  push:
    branches:
      - main

jobs:
  release:
    permissions:
      contents: write
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Configure Git
        run: |
          git config user.name "${GITHUB_ACTOR}"
          git config user.email "${GITHUB_ACTOR}@users.noreply.github.com"

      - name: Release brouter and brouter-web charts
        uses: helm/chart-releaser-action@v1.7.0
        with:
          charts_dir: brouter-charts
          skip_existing: true
        env:
          CR_TOKEN: "${{ secrets.GITHUB_TOKEN }}"

      - name: Update Helm dependencies for brouter-stack
        run: |
          helm repo add brouter-stack https://joe-akeem.github.io/brouter-helm-stack/
          helm repo update
          cd brouter-stack-charts/brouter-stack
          helm dependency update

      - name: Release brouter-stack charts
        uses: helm/chart-releaser-action@v1.7.0
        with:
          charts_dir: brouter-stack-charts
          skip_existing: true
        env:
          CR_TOKEN: "${{ secrets.GITHUB_TOKEN }}"
